name: ArchiveReader
options:
  bundleIdPrefix: com.archivereader
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"

targets:
  ArchiveReader:
    type: application
    platform: iOS
    sources:
      - path: ArchiveReader
        excludes:
          - "Resources/JavaScript/**"
      - path: ArchiveReader/Resources/JavaScript
        buildPhase: resources
        type: folder
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.archivereader.app
        INFOPLIST_FILE: ArchiveReader/Info.plist
        CODE_SIGN_ENTITLEMENTS: ArchiveReader/ArchiveReader.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: ArchiveReader/ArchiveReader.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.archivereader
    info:
      path: ArchiveReader/Info.plist
      properties:
        CFBundleDisplayName: Archive Reader
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - archivereader
            CFBundleURLName: com.archivereader.app
        ITSAppUsesNonExemptEncryption: false
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    dependencies:
      - target: ArchiveReaderShareExtension
        embed: true

  ArchiveReaderShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: ArchiveReaderShareExtension
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.archivereader.app.ShareExtension
        INFOPLIST_FILE: ArchiveReaderShareExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: ArchiveReaderShareExtension/ArchiveReaderShareExtension.entitlements
    entitlements:
      path: ArchiveReaderShareExtension/ArchiveReaderShareExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.archivereader
    info:
      path: ArchiveReaderShareExtension/Info.plist
      properties:
        CFBundleDisplayName: Archive Reader
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsWebURLWithMaxCount: 1
              NSExtensionActivationSupportsWebPageWithMaxCount: 1
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShareViewController
